
name: Simulate STATUS workflow

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  simulate-status-workflow:
    runs-on: ubuntu-22.04
    permissions:
      statuses: write
    steps:
      - run: echo 'add-status-success'
      - run: echo "The GitHub workflow_run '${{ github.event.workflow_run.name }}'' failed on the renovate-updates branch against master -> * ${{ github.event.workflow_run.html_url }}"
      - run: |
          echo 'Simulate STATUS workflow start...'
          
          echo 'Adding pending STATUS'
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
             -f "state=pending" -f "target_url=https://example.com/build/status" -f "description=The build pending!" -f "context=simulate-status-workflow"
          
          echo 'Sleep a couple of minustes'
          sleep 30s
          
          echo 'Updating the STATUS tu sucess'
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }} \
             -f "state=success" -f "target_url=https://example.com/build/status" -f "description=The build pending!" -f "context=simulate-status-workflow"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
